### ISSUE TITLE
When i enter invalid mnemonic the wallet freezes

### ISSUE THREAD

**Issue by ddeath** [vacuumlabs/cardanolite#134]
If I enter `civil void tool perfect avocado sweet immense fluid arrow aerobic boil flash civil void tool perfect avocado sweet immense fluid arrow aerobic boil flash boil flash house`, the wallet allows to "login" but it will get stuck on loading screen with error in console `Uncaught (in promise) Error: Invalid mnemonic checks`

**Comment by refi93** [comment]
fixed in  #135
